/**
 * @constant { object } AJVKeywords
 *      This is a list of keywords that come with AJV, when adding a keyword check against this list as appropriate to keep from adding duplicates, b/c AJV will throw a fit
 *  @property { string[] } standard: JSON Schema Keywords
 *      These are the keywords defined by the JSON Schema specification itself. Ajv, being a compliant validator, supports these out of the box
 *  @property { string[] } package: ajv-keywords Package Keywords
 *      These keywords are not part of the standard JSON Schema specification but are provided by the ajv-keywords package to extend Ajv's capabilities
 */
const AJVKeywords = Object.freeze({
    standard: [
        'type',
        'enum',
        'const',
        'multipleOf',
        'maximum',
        'exclusiveMaximum',
        'minimum',
        'exclusiveMinimum',
        'maxLength',
        'minLength',
        'pattern',
        'items',
        'prefixItems',
        'additionalItems',
        'contains',
        'maxItems',
        'minItems',
        'uniqueItems',
        'maxProperties',
        'minProperties',
        'required',
        'properties',
        'patternProperties',
        'additionalProperties',
        'dependencies',
        'dependentRequired',
        'dependentSchemas',
        'propertyNames',
        'if',
        'then',
        'else',
        'allOf',
        'anyOf',
        'oneOf',
        'not',
        'format',
        'title',
        'description',
        'default',
        'examples',
        'readOnly',
        'writeOnly',
        'deprecated',
        '$id',
        '$schema',
        '$ref',
        '$defs',
        '$comment',
        '$anchor',
        '$dynamicAnchor',
        '$dynamicRef',
        'unevaluatedItems',
        'unevaluatedProperties',
    ],
    package: [
        'allRequired',
        'anyRequired',
        'oneRequired',
        'patternRequired',
        'prohibited',
        'deepProperties',
        'deepRequired',
        'dynamicDefaults',
        'typeof',
        'instanceof',
        'range',
        'exclusiveRange',
        'regexp',
        'transform',
        'trim',
        'trimStart',
        'trimEnd',
        'toLowerCase',
        'toUpperCase',
        'toEnumCase',
        'uniqueItemProperties',
        'switch',
        'select'
    ]
})

export { AJVKeywords }